### ISSUE TITLE
Decrease resource usage of WindowServer due to Prismatik on macOS

### ISSUE THREAD

**Issue by danielcompton** [psieg/Lightpack#102]
#101 significantly decreases the CPU time required by Prismatik. However, the WindowServer process is also used by Prismatik, and Prismatik causes higher resource usage. When Prismatik is not running, it uses 2-3% CPU, when Prismatik is running, it hovers around 20%.

I'm not really sure if there are any ways to call the API more cheaply, but it's an avenue for future improvement.

**Comment by psieg** [comment]
again, no mac here, so any mac developer is invited to step up

**Comment by denniswander** [comment]
Just installed the new version after a thorough uninstall and I'm actually experiencing slightly worse FPS on macOS 10.12.4 compared to the old version. Also, the severe impact on system performance is unchanged, most easily seen in revealing the hidden Dock (goes with a lot of stutter). 

I'm also not a dev by any means, but I'd be happy to do any testing if desired.

**Comment by psieg** [comment]
I'm guessing this is fixed with the new mac grabber :)

**Comment by daysonhw** [comment]
> Try this [build](https://github.com/zomfg/Lightpack/releases/download/5.11.2.18-grab-alpha/Prismatik-grab-test.dmg)

The new grab works well in my device, it was 20 FPS and making it lagging after using new grab u build it's up to 80 FPS and fluent. Thank you for your contribution

**Comment by daysonhw** [comment]
### For the people have some issues please select the Mac AV (grab) in the exprimental in the late 5.11.2.18. 
**BTW the version that zomfg build have problem of inconsistent display.**

**Comment by zomfg** [comment]
@daysonhw you should not be needing that build as the current release from here has everything I added for MacOS and is more stable.

Also, what kind of inconsistent display are you talking about?
The only issue I know of is that on some macs the bottom part of the capture has grey artifacts, which is a bug somewhere in MacOS.
If that is your problem try [this build](https://github.com/zomfg/Lightpack/releases/download/5.11.2.18-grab-alpha/Prismatik-safe-scale.dmg)
If the whole thing is freaking out, use [this](https://www.partsnotincluded.com/calculating-adalight-framerate-limits/) to adjust your baud rate.

**Comment by daysonhw** [comment]
@zomfg 
Thank you for your reply, The current release looks fine with Mac AV grab ( is that your woks? the default Mac CG grab is still lagging) , except proformance problem. The previous build you made it's FPS can climb up to 750 and only 25% of GPU using rate, the latest build with Mac AV only 70 FPS and 100% of GPU using rate.

the inconsistent display in your build 5.11.2.17 is      my monitor is 4k and scaled to 1080p, the previous build you made did not respond to scaled resolution, it only grab 1/4 of my screen's area, not all of it.

**Comment by zomfg** [comment]
With different test builds around that have same version number I'm bit lost with which build has what problem, just to make sure, could you list links (not just versions) to the builds you tested with, that would help a lot. Something like:
- [build A](https://github.com/psieg/Lightpack/releases/download/5.11.2.19/Prismatik_5.11.2.19_298.dmg) :  X fps with Y % cpu/gpu, has Z bug
- etc

also what MacOS version do you use? and your mac specs

**Comment by daysonhw** [comment]
zomfg / Lightpack 5.11.2.17 750 FPS with 25% of GPU Problem: Only grab 1/4 of my screen's area (4K to 1080p)
psieg / Lightpack 5.11.2.19 in Mac CG mode: 20 FPS with 100% CPU ( Causing GUI lag )
psieg / Lightpack 5.11.2.19 in Mac AV mode: 70FPS with 100% GPU

10.14.6 , Hackintosh with 9400F and RX 580.

**Comment by zomfg** [comment]
Thank you
What kind of grab interval are you using and how many LEDs?

**Comment by daysonhw** [comment]
I tried many defferent kinds of interval but the GPU using rate didn't change with it, even the grab interval(FPS) was down to half of the maximum(test in 1 ms)
60 LEDs

**Comment by zomfg** [comment]
1. The version that reported 750 FPS was a "quick" and dirty test and did not report the actual FPS, so that value doesn't mean much I'm afraid.

2. I don't have a mac with a 4K display, best I can do 2560x1440 on a 2013 iMac or 3440x1440 in a VM (no real GPU), but on both I max out at around 70-90 FPS which looks to me like an absolute limit for this method (at least for now, maybe forever on current hardware/software combination).

3. There's absolutely no reason/advantage to target FPS above your refresh rate, and I'd recommend something around half refresh rate for 60Hz for ex.

4. Try [this tool](https://github.com/zomfg/Lightpack/releases/download/5.11.2.18-grab-alpha/AVScreenShack_10.15.app.zip), this is a stripped down display capture code without Prismatik's overhead, all it does is getting frames, no color processing. Could you compare this to Prismatik at 15, 30, 60, your refresh rate, 1000 target FPS and report results? IF you are using HiDPI on the captured display, so retina-1080p on 4K for ex, do set the scale to `0,05/ratio`, for 1080p@4k (3840/1920=2) that would be `0,05/2=0,025` (type number and press enter)
