### ISSUE TITLE
LED color order change 

### ISSUE THREAD

**Issue by Viker** [psieg/Lightpack#105]
Hi. I am just wondering if there is a way to change the color order for the leds from RGB to GBR or some other combination. 

It is possible in ambibox. 

Thank you in advance for the update. It is great.

**Comment by twistedminddnb** [comment]
I have the exact same question.

Hope to get reply soon. Otherwise i might go the hyperion route which is not necessary in my case and more expensive.

I have searched for ledstream alterations but i cant get it to work.

**Comment by twistedminddnb** [comment]
On another note...

I have testet the order switch in smbibox and it seems to work but somehow the colors in between are not right and the last led is alway different. In screen grabbing mode its fluckering.

I am out of ideas

**Comment by twistedminddnb** [comment]
I have found the answer.

I only have  chekced the version released 2 days ago.

It is inside the device wizard.

Where you select Com and Baud Rate is also the Color order.

However it is still not working for me.

Here is what was and what is working for me now.

First I had the arduino loaded with the LEDstrem.ped from adalight.

Prismatik unoffiacial = Wrong colors in mood lamp but steady. Flickering on screen grabbing.

Prismatik unofficial (New Version) = Colors still are messed up after changing in device wizard.
If I remember correct the Main colors where right but the in between ones not really

Ambibox set to BGR = Correct colors but they would change after 3 sec although steady backround was selected. Also flickering during screen grabbing.

Processing: Flickering during screen grabbing and colorswirl.

Because i had ordered a new strip, i wanted to follow up on the flicker issue because i thought it would be bad to have a working strip but still flicker issue.

I found this FastlLED sketch.

https://gist.github.com/derpeter/025c7adaaf70886005ab

Ambibox = with this sketch the flickering is gone and the BGR setting in ambibox works like expected. As long the sketch has the color order set on RGB and Ambibox to BGR. I haver tried setting it to BGR and Ambibox to RGB but somehow it was wrong. Maybe im cunfusing thigs here :) But it works now with right colors without flickering.

Prismatik (new version) = Ithought this might now also work with prismatik. But its the same as above.
No real screen grabbing. everthing stay white mostly. Colors in between not matching in mood lamp.

I am least happy to have found a solution but think that Prismatik might be more friendly on cpu.

However in win 10 Ambibox seems to run also in games without Playclaw.

But thank you so much for your effort to make prismatik a better programm.

**Comment by Viker** [comment]
Thank you very much for the effort and the well documented reply. 

I noticed that the setting exists for the other options but Lightpack. I couldn't get the Lightpack to lightup with the other settings. 

How do I flash these ebay Ambibox lights with arduino code?

**Comment by dmadison** [comment]
What devices are you two using?

I have 5.11.2.11 installed and the color order settings work properly for me with the Adalight protocol.

**Comment by Viker** [comment]
I have a generic Lightpack off ebay. Got it to work with Hyperion in the end.

**Comment by twistedminddnb** [comment]
I got it to work with another adalight protocol.

Color change works in prismatik and ambibox.

But on adalight the smoothenes setting seems not to be available.

For the few games that do not work with ambibox i use prismatik.

Overall i like ambibox better for my setup.

Cant get the real hectic color change under control in prismatik.

**Comment by psieg** [comment]
It seems your clone does not follow the Lightpack protocol properly (color order, device-side smoothing)
