### ISSUE TITLE
Incorrect number of LEDs in white balance adjustment

### ISSUE THREAD

**Issue by dmadison** [psieg/Lightpack#124]
I just tried out the new white balance portion of the configuration wizard (#86, #95), which looks _great_ by the way, but I noticed my framerate was in the single digits and lagging behind by several seconds. I sniffed the serial data and it seems Prismatik is sending 255 LEDs worth of data per frame, regardless of the LED count setting. After leaving the configuration wizard the LEDs/frame drops back to normal levels.

**Comment by psieg** [comment]
As it only sends them rarely and just during the setup wizard this might be acceptable. I'll take a look at whether the number of LEDs is easily obtained in that situation (part of the code).
If it's low effort I'll fix it

**Comment by dmadison** [comment]
It's probably more of an issue for 3rd party devices because Prismatik doesn't have any checks for serial buffering. For my adalight setup you need to wait ~10 seconds after dragging the slider for the lights to update to the most recent value.

**Comment by Domush** [comment]
On my adalight setup the 255 LED data prevents the lights from coming on at all because the LED data doesn't match the expected # of lights. This meant I had to stop using Prismatik altogether because I have no way to light balance without manually adjusting all 34 zones, which is silly.

It should be trivial to capture the number of LEDs from the previous input and send the correct # of LED commands. After all, why ask for the # of LEDs if it's just going to ignore the answer?

Ideally I'd love to see the white balance incorporated into the main settings, even if it only supports a "change all lights" option. AmbiBox has this feature, if incorporating their code will help.

**Comment by dmadison** [comment]
Can confirm, testing with 5.11.2.15 the correct number of LEDs are sent to the device!
