### ISSUE TITLE
Program closes after setup (and doesn't want to start again!)

### ISSUE THREAD

**Issue by darkcheater** [psieg/Lightpack#142]
Hi,
I experience the following Problem.
I tried running this on Windows 10 x64 with my Adalight setup.
The setup and the calibration works, my LEDs light up correctly.
When I however click finish after the calibration process, the leds keep shining and the program closes.
It is shown at the quick launch bar but goes away when I move my mouse over the icon.
When I try starting it again, it just shows up at the quick launch bar and closes when I move my mouse over it.
I have attached the log file.
Maybe someone can tell me, whats going on.
[Prismatik.0.log](https://github.com/psieg/Lightpack/files/1403197/Prismatik.0.log)

Thanks!

**Comment by psieg** [comment]
The log does not show a clear error. What did you name your Profile? How many Profiles do you have?

**Comment by fgblomqvist** [comment]
I experience this as well. Was running just fine on Ubuntu GNOME 17.04, but now when I upgraded to Ubuntu 17.10 (which comes with GNOME by default) the tray icon does not show up. I deleted my old profile and was able to get the setup window to show up when I started Prismatik the next time. After the full setup, Prismatik keeps running (leds are white) but there is no tray icon. If I restart it, it runs but still no tray icon (and leds remain white).

My issue is obviously slightly different from the OP's, but maybe they are related? I only have 2 lines in the log:
> 
2017_10_30 12:50:55:408 Prismatik 5.11.2.13
12:50:55:619 Warning: Fail load translation for locale "en_US" pathToLocale ":/translations/en_US"
>

**Comment by fgblomqvist** [comment]
Figured it out: due to the system tray changes in GNOME 3.26, you now need the "KStatusNotifierItem/AppIndicator Support" extension for the tray icon for Prismatik to show up (and for most other apps too). The extension itself is a bit buggy (have to turn it on and off sometimes for the indicators to show up), but once you get it to work the Prismatik icon shows up and you can open the main interface through it.

Side note to dev: launching Prismatik while Prismatik is already running should open the main interface.
