### ISSUE TITLE
Windows 10 update breaks F.LUX integration

### ISSUE THREAD

**Issue by Domoer8** [psieg/Lightpack#190]
Just went through a standard system update with Windows 10 that broke the functionality of F.LUX integration.  Checking the f.lux box in settings would not change the mood of the led lights. When I rolled back my windows update, everything returned to normal.

**Comment by psieg** [comment]
AFAIR flux needs to be re-enabled for the "full color range" thing after windows updates. Once that is done, the Prismatik mechanism works again

**Comment by Domoer8** [comment]
I uninstalled flux, restarted, reinstalled and restarted.  I got the messages both times about changing the color range after restarting.  The flux option in prismatik is still not working.

**Comment by psieg** [comment]
You got the message both times? So f.lux is not in extended mode?

**Comment by Domoer8** [comment]
As soon as I install flux it tells me that when I restart I will be using
extended colors. I believe I am in extended mode because I have access to
the colors beyond “3400K”.

**Comment by johnmrushing** [comment]
Same issue. f.lux and prismatik both reinstalled and expanded color enabled.

https://imgur.com/2Z5INnb

**Comment by Garwinski** [comment]
Doesnt work for me either. (I have a AMD Fury X connected with DisplayPort, if that is any help. Here are some relevant screenshots: https://imgur.com/a/4xBvu60 )

**Comment by psieg** [comment]
I managed to reproduce the issue. I updated f.lux after without (or rather, long after) a Windows build upgrade.
Since I don't know what happened, I'm not sure how to fix it though

**Comment by Garwinski** [comment]
Something interesting: When installing f.lux through the Windows Store, Prismatik _does_ pick up the color changes, and it works like intended! I am not sure if this has to do with the Windows Store, or that the Prismatik version is 4.66 instead of the newest, 4.76. 

I was spurred on to try F.lux through the Windows Store when I saw this comment: 

> "Seems like I solved my problem by uninstalling the app and then re-installing from the windows store.
> 
> Hope it helps"
> 

https://forum.justgetflux.com/topic/6339/after-win10-april-update-flux-sometimes-swich-on-off-for-seconds

I also ran into this when looking for possible new features in Windows 1803 that could interfere with color-changing programs: 

https://www.windowscentral.com/how-use-color-filters-windows-10-april-2018-update

I tried these filters, and noticed that they are picked up by Prismatik with no problems, so they do work very differently from Night Light (and probably F.lux) So then I saw this part:

"Furthermore, color filters work at a system level, meaning that it's a feature that will work with the elements of Windows 10 as well as with apps, including Microsoft Store apps and classic (win32) programs."

Could this new color-filter feature have anything to do with it? Maybe it changed some fundamental things for color-filter apps like F.lux which now hinders Prismatik from capturing the chang, but as an app through the store, it works. 

 My speculation about the cause might all be gibberish, but I did not want to leave it out, because it could be relevant.

**Comment by locki-cz** [comment]
i tshoot few days and i found:
first must be runned f.lux and then prismatik :) after that it work like charm, in windows is imposible change which program starts first automaticaly, 3rd party sw must be used or use some sheduler in windows

**Comment by psieg** [comment]
Considered fixed since we have night light support now

**Comment by x-trend1** [comment]
How it works? What ill need to do for flux sync?

**Comment by Domoer8** [comment]
Yeah, after another windows update, Flux is acting up again.  Same issue as before, lights not matching up with screen color temperature.  I've tried uninstalling/reinstalling both apps, unlocked full color range, tried the version from the flux website, AND the one from the windows store.  Nothing.  I guess I'll have to use Night Light for now, but I would really appreciate flux integration to work again.  Flux offers so much more customization over something like Night Light.

**Comment by Domoer8** [comment]
[Prismatik.4.log](https://github.com/psieg/Lightpack/files/3083646/Prismatik.4.log)
I'm seeing:
00:18:46:906 Debug: Settings: "Grab/IsApplyColorTemperatureEnabled" not found. Set it to default value:  "false"
00:18:46:906 Debug: Settings: "Grab/ColorTemperature" not found. Set it to default value:  "6500"

**Comment by BodrickLight** [comment]
f.lux integration doesn't seem to work for me either. Running f.lux v4.100 and Prismatik 5.2.11.19 in the Desktop Duplication mode.

**Comment by x-trend1** [comment]
It works nice in SunsetScreen !

**Comment by memehammad** [comment]
Still having this issue. Newest version of Prismatik and f.lux. Reinstalling doesnt help.
