### ISSUE TITLE
Can`t get Adalight to run, no lights, anything, Ambibox has no problem, help please.

### ISSUE THREAD

**Issue by WalterBusseler** [psieg/Lightpack#247]
Com4 is set, 9600 Baud is set, RGB is set like in Ambibox
39 LEDS are set like in Ambibox
No lights working ..... nothing
USB Controller is CH340 on Com4
Latest Win 10, CH340 Driver was installed from Windows automaticly
Ambibox works directly, Prismatik not, what do i wrong
Tryed with the wizard, no single LED working, do i something wrong ?
Thanks for your help

**Comment by WalterBusseler** [comment]
Com4 is set, 9600 Baud is set, RGB is set like in Ambibox
39 LEDS are set like in Ambibox
No lights working ..... nothing
USB Controller is CH340 on Com4
Ambibox works directly, Prismatik not, what do i wrong
Thanks for your help

**Comment by zomfg** [comment]
What framerate are you using in Prismatik?
You should be able to use 500k baud rate with ch340.
Could be your firmware.

**Comment by johnnyxtheman** [comment]
same here but i use ambibox software and have it connected on com 6. 
i have the ws2812b  5050 dream color e60 4 meter 300 leds
installed on a laptop to use for samsung qles9 tv when this is used as a monitor because samsung tv does not support the one i have so than is use the laptop to whats movies on it. 
but after setting up everything, and the ambibox software, the tutorial says after i had closed the wizzard and could test it but how to test it??? just minimize the software and play a movie .... if so i did this but no light ar lighing up ... stay dark .. i am already  2 days buzzy to get this to work bu no luck sofar ...
if i had known that it takes so must more dan just plug and play ..well than i did not boutn tnis

so anyone know's a solutuion ?

**Comment by TheMcSebi** [comment]
How much power are you supplying your strip with?

**Comment by jellewie** [comment]
> How much power are you supplying your strip with?

Looking at the WS2812B datasheet for example shows us that each color LED (at full power) uses 20mAh.
each led has 3 LEDs inside; Red Green and Blue. thus each LED of the ws2812B uses 60mAh = 0.060A
My strip has 131 LEDs and 131*0.06A = 7.86A (this is full brightness white)

This strip runs at 5V, and we know W=V*I thus 7.86A*5V=39.3Watt (An average USB 2 port delivers 2A and thus 10Watt, thus we need an external power supply)


On a side note, the WS2812B has an arrow on the data pin, and thus the data is directional (Power is not) but if the power is connected in reverse (5V on GND pin) the led(s) will be blown up, most of the times just the first one

**Comment by psieg** [comment]
Closing some old issues, sorry for the spam, if any.

**Comment by zdunex25** [comment]
@WalterBusseler did you manage to solve your problem, i face the same exact issue right now
@jellewie posted edit not that he resolved the issue but no details
thanks in advance guys

**Comment by Ibraham-Sheih** [comment]
здравствуйте, что делать если при подаче питания на ленту загораются 2 первых светодиода, и при подключении и настройке всего остального в программе Ambibox написано Adalight не подключено, и ничего не загорается?
