### ISSUE TITLE
Feature request: Connect to home assistant

### ISSUE THREAD

**Issue by daniel9522** [psieg/Lightpack#293]
Please look into away to connect lightpack with home Assistant server
Thank you

Some useful links
https://www.home-assistant.io
https://github.com/mihalski/py-lightpack/blob/master/README.md
https://github.com/kklemm91/Lightpack-HASS
https://github.com/renemarc/home-assistant-config/blob/master/custom_components/light/lightpack.py

Please look into it thank you

**Comment by zomfg** [comment]
Funny you should ask...
Thanks for the links! Do those integrations not work any more or do you mean something else?

**Comment by daniel9522** [comment]
Unfortunately none of them work at least anymore and even when they did
work they only had partial features
If it would be possible to add both profiles and brightness control.
I only asked you to please look into as you are still updating the software
(truly do appreciate) and thanks for the reply

**Comment by zomfg** [comment]
[a pre-pre-alpha test version](https://github.com/zomfg/home-assistant-prismatik)
colors, brightness, profiles seem to work on 0.104.3
it's super basic, but should work ok if you keep it in moodlight mode

**Comment by spacemanspiff2007** [comment]
Wouldn't a more generic approach better (like rest/mqtt/etc.) since there are more automation systems out there than HA.

**Comment by zomfg** [comment]
Not really, or by much.
MQTT, REST etc, are just generic communication channels, it still would be on you to implement Prismatik API on HA/OpenHab/node-red/whatever.
And it turns out Prismatik already uses one of the most generic channels: a simple tcp socket.
In HA, out of the box, you could talk to it with something like [this](https://community.home-assistant.io/t/sending-tcp-packets-to-a-device/68076/50).
It might be better doing it through node-red.
Also, I don't know how would you make a full blown RGB lamp (color wheel and all) in HA with only MQTT/YAML (and without a custom UI card), if you have a link for that... If it's doable, it's probably also doable with the socket.

That being said, I was excited when I saw MQTT support announced for Qt a while ago, but when I saw that it requires an account with a special automation license, I dropped the idea. Also the amount of work would be bigger than that native mini integration in HA, so I haven't looked into third party multiplatform libraries either.

**Comment by zomfg** [comment]
[This](https://github.com/zomfg/home-assistant-prismatik) is reasonably usable now.

**Comment by daniel9522** [comment]
Thanks for this man I just tried it out and It works way better than expected like really easy to install and get going truly appreciate all your work man 
Thank you
