### ISSUE TITLE
Latest update (5.11.2.21) caused AV to trip and remove Prismatik

### ISSUE THREAD

**Issue by bob-oey** [psieg/Lightpack#295]
After an automated update, Windows 10 Defender detected the Prismatik binary as a Trojan:Win32/Occamy.C. Directly after, my system gave a BSOD with the error "driver power state failure".

**Comment by fharni** [comment]
On my system I can not download this version. Chrome tells me, that a virus was detected and deletes the download.

**Comment by psieg** [comment]
It's false positive, see #292.
I tried getting around it in version .21, and everyone but microsoft thinks it's okay: https://www.virustotal.com/gui/file/8652af4d6560e9a228e9aeaa281d12104ad9defc42519dda788cc26a0a4b3f6e/detection

I have no way to make them reconsider.

**Comment by zomfg** [comment]
@psieg maybe a (temporary) solution would be to disable autoupdate and just display a popup with a 
release link?

**Comment by psieg** [comment]
The problem is there's no disable/enable option here. Either the package includes the helper and can do auto updates (enabled or not) or it doesn't and can't, which means it will never be able to.
I still haven't enabled auto-update (or notification) for users still on .19.\

So yes, there's the option of removing auto-update altogether, but then there's really no hope of bringing it back in the future.

**Comment by zomfg** [comment]
Beats freaking people out with trojans 😄 but if the "new version" popup is there until the update is done people wont miss it.

I'm having trouble building the installer (script.iss is giving a vague message about something missing), but the binaries I scan (ms av) up until that point are all good. The .21 release installer is raising the alarm, the .20 isn't.
I'm building with VS2019 / WinSDK 10.0.18362.0, did you try different versions in case that changes the binary signature in a positive way?

**Comment by zomfg** [comment]
How about a portable version in a zip along the installer.exe? (basically release build folder)

**Comment by psieg** [comment]
I got rid of the detection warning on all binaries by removing the static linkage on the updater tool. Turns out they are back now: https://www.virustotal.com/gui/file/4812f542c160aa1f2c82425387cc705ab44f7e4676e68df5ce78790f8e23a620/detection

Fun thing is, Microsoft considers the installer package evil, but not the tool (nor Prismatik.exe). At the same time, those that detect the tool do not detect the installer. WTF.

**Comment by psieg** [comment]
@zomfg If you switch to static linkage (/MT) and use the static openssl binary (basically undo https://github.com/psieg/UpdateElevate/commit/58103713c73a78802950acad62ade8a17f514bc6), does it trigger?
Local scanning with windows defender didn't ever trigger on any of my binaries, upload them to virustotal...

**Comment by psieg** [comment]
With much discontent I added a build based on #298 to the downloads section.

**Comment by zomfg** [comment]
@psieg haven't retried Prismatik yet, but here are my UpdateElevate builds
[/MTd](https://www.virustotal.com/gui/file/1e303db1c2c6a009897f966e56a0b8cb9a9f4eab78bd6eeec5bd353806a39e86/detection)
[/MT](https://www.virustotal.com/gui/file/f5c2a7f24696f06b8e91ced981802e651f5093cdd48d0978440229a7bcad4835/detection)
green all around
VS2019 16.4.4 / WinSDK10 v142 / OpenSSL 1.1.1d

**Comment by zomfg** [comment]
[Prismatik.exe /MT + UpdateElevate@2149071](https://www.virustotal.com/gui/file/e89706c531e2f0786692869679d19de5c84b9d9d7ddd88a69c44c0a19b7817b0/detection)
[Prismatik.exe /MD + UpdateElevate@875f09e](https://www.virustotal.com/gui/file/af3d4bfbfd90c6417ed896afb8cef93918e3c5dabc11314ef2a232ec33f62620/detection)

**Comment by zomfg** [comment]
here is my dist_win/content + installer
[Prismatik /MD + UpdateElevate@875f09e](https://github.com/zomfg/Lightpack/releases/download/5.11.2.18-grab-alpha/5.11.2.21_content_MD.rar)
[Prismatik /MT + UpdateElevate@2149071](https://github.com/zomfg/Lightpack/releases/download/5.11.2.18-grab-alpha/5.11.2.21_content_MT.rar)
individual exes show green, but both installers [trigger McAfee](https://www.virustotal.com/gui/file/42cda45857bfae14a52c66f2d67b97d7af8f7e90262a22ea63bebddb3ad68218/detection) with `BehavesLike.Win32.Generic.tc`

I had to remove hook32 and ssl lines from .iss as they weren't in content

**Comment by zomfg** [comment]
I just made an .msi package with [this extension](https://marketplace.visualstudio.com/items?itemName=VisualStudioClient.MicrosoftVisualStudio2017InstallerProjects), it came out [green](https://www.virustotal.com/gui/file/ec7d30848437bab35a640721b8b722a5b167f21c5287273a298625aae9f2a1a3/detection)

**Comment by psieg** [comment]
Just found out Microsoft no longer considers the .21 installer malicious: https://www.virustotal.com/gui/file/8652af4d6560e9a228e9aeaa281d12104ad9defc42519dda788cc26a0a4b3f6e/detection

Could someone scan on their local Windows Defender to confirm pelase? Mine has never triggered on anything...

I might just enable auto-update .20 -> .21.
I also submitted some files to Microsoft to appeal, let's see if someone will look at it...

**Comment by zomfg** [comment]
scanning both .21 installers doesn't trigger mine (all up to date)

**Comment by psieg** [comment]
So it looks like the version that doesn't statically link openssl is fine by most AVs. For recent releases I had to submit the setup to MS to make them whitelist the installer, but I haven't heard of issues since.

I guess I'll have to keep VirusTotal-ing the setup files and wait with the auto update some time after making the binary available...
