### ISSUE TITLE
Overbrightning bad?

### ISSUE THREAD

**Issue by HighOnBuffs** [psieg/Lightpack#307]
Hi i tried Prismatik and the outdated Ambibox and discovered that Prismatik is super dim without setting the overbrightning to 30+%.
Is that a bad thing? I thought if i force over brightning, i lower the potential effect of the ambilight when dark scenes are darker and bright ones are brighter, like homogenizing the effect?
Is that true or should i not worry about it and set it to 100?

Sorry if this is the wrong place to ask such a question but i was looking everywhere and figured i ask the creators of the fork for the best outcome.

Thanks a lot!

**Comment by zomfg** [comment]
I would not say it's bad, it scales color components proportionally, so the final color should remain close to the original, just brighter. It could look wrong(er) if your display calibration does not match your LEDs (also true without over brightening).  

This is the formula behind it, you can try it on some colors to see if it fits your needs (or just use your eyes)
https://github.com/psieg/Lightpack/blob/ce0c4b22af3fd4d348a791ae9a3a857fbcd083c7/Software/src/GrabManager.cpp#L459-L467

**Comment by HighOnBuffs** [comment]
Ok so what you are saying is it still shows brighter and dimer as those havent really anything to do with darker or brighter but with the right color tone?

Does that mean i can put overbrightning to 100% without any negative effects, if i think my strip is too dim otherwise?

I was mainly asking as i have a 30/m strip behind my PC monitor (about 20cm away from the wall) and was thinking if the upgrade to 60/m was worth it to make it brighter but when i put over brightning up i feel its fine as it is. Or do you think its worth upgrading for a better effect?

Thanks!

**Comment by zomfg** [comment]
It only gets brighter, it does not make it more contrasted (brighter brights and dimmer dims), for example RGB 20,10,5 will become 120,60,30 (try it [here](https://www.rapidtables.com/web/color/RGB_Color.html#color-picker))

If it looks and matches your display better, go ahead and use it, that's why it's there.

60 will give you better color resolution, more detail... not mind blowing but given the price I'd do it

**Comment by HighOnBuffs** [comment]
Ok great to know!

Yeah the upgrade would cost me around 70€ (40 for the LED strip and 30 for the 5V 6A power supply) so i was not sure if ts wort it for me. 

Btw you seem to really know your way around ambilight, is it normal to feed power into the strip from both ends? I ordered a 60/m 2m strip and the guy who sold it to me also sold me a 5V 6A power supply with some adapter cable to put it on both the ends of the strip so th ewhite colors are uniform. Is that normal?

Thanks!

**Comment by zomfg** [comment]
on aliexpress 60/m strip is around 6 euro/m, cheap PSU as well, I hope your seller sells super quality stuff with those prices.

It is not abnormal. Depending on the amount of copper and, in term, the resistance of the strip you might need to power from both ends in order to reduce the voltage drop (the further you are from the power source the dimmer lens will be if there is not enough copper). Another "trick" is to power from the middle of the strip, might be cleaner (depending on LEDs the data still has to be fed from one end since it's directional)

**Comment by HighOnBuffs** [comment]
I hope so too haha. Im sure he sells it for more then its worth but i dont have any tool sfor soldering so i have to take it i guess.

Ok i was curious about it as my 30/m strip all WS2812b btw. doesnt need to be powered from both sides.

Thanks for the insight!

**Comment by zomfg** [comment]
ws2812b from ali come with a 3 pin connector on both ends
soldering kits are cheap too (even on amazon)

**Comment by HighOnBuffs** [comment]
Hm yeah i might look into it and just refund the kit for now. My 30/m works fine for now. 
I eventually get a new Monitor anyways at some point then i might upgrade to 60/m.

Thanks for all the knowledge!
