### ISSUE TITLE
Android App won't connect

### ISSUE THREAD

**Issue by jkantr** [psieg/Lightpack#34]
Android app complains about "the API version is not the same". I imagine this is because of the new 6.0.0 versioning upstream? Not sure what the work around would be here. I will try to find an archived version of the apk for now.

Edit: Although now that I'm looking.. the android apk hasn't been updated since July 2014, so it isn't that.

**Comment by jkantr** [comment]
Alright, well I see that with some added features the API version was bumped to 1.5 from 1.4

Is this a full breaking incompatibility to the existing android app? Is there an alternative that I'm missing?

**Comment by psieg** [comment]
Hi,

the change is a minor addition (#13), which is why only the minor version was increased (see [semver.org](http://semver.org/)). So IMO the best option is to contact the creator of the app to accept 1.X with X >= 4 as API version.

On the other hand this is a fork and we don't know what the Lightpack people are going to do if they change something - they might release a different 1.5 someday. Assuming you're talking about the "Prismatik Controller" app, I tried using it with API version 1.4.1, so that would be another option. This is what was done in PR #27 with the Lightpack firmware, because it happened to work. BUT (a) unpublishing 1.5 is bad (b) it might break existing clients which don't expect another number after the minor version.

**Comment by psieg** [comment]
Fixed in ba68f77a1502ea342f57c0449ad03c5731be74fa. @damianromanowski you might want to adjust your scripts for the next release - check for Prismatik API 2.0
