### ISSUE TITLE
Flickering darker areas

### ISSUE THREAD

**Issue by Kas152** [psieg/Lightpack#398]
Since the new update when prismastik scans a darker color, the leds tend to ficker from green to red very faintly. In the day you don't really notice it, but at night it is very distracting, so i dongraded to the previous version for now. 
I presume it has to do with the added function of dithering, as this was not there before. The colors are more accurate that way though, it seems. Only i couldn't find and option to change this setting. Any suggestions here? Thanks in advance! @psieg Also a big thanks for leading an making this program!!

**Comment by krmrbtn** [comment]
It also flickers when scrolling a white page. I assume it pics colors from wrong zones. For me, it's the bottom of the screen. I downgraded for now.

**Comment by Chalapacho** [comment]
I got the same problem, but the flickering appears all the time, even in bright areas. Downgrading to version 5.11.2.23 resolved the issue.

Some information that might help:
I use the Adalight arduino script, with four CableMod Addressable LED strips. I tried to reduce my lighting setup to one LED strip and used screen grabbing from only one monitor instead of two, but it didn't change anything. Reducing the grab interval slowed the flickering rate down. Changing the capture source also didn't help.

**Comment by FiraWolf** [comment]
Got the flickering as well. Most prominent on static / non-moving scenes in youtube/twitch videos.

**Comment by zomfg** [comment]
also very visible on moodlamps for me, rolling back to b13dec9 fixes that

**Comment by psieg** [comment]
Hm, I guess we should add a setting for dithering then. From how I understand it, it shouldn't add flickering on static scenes though as there's no carryover between frames...

**Comment by zomfg** [comment]
prismatik probably captures the tiny color variations due to video compression so it's not static static
it's also very noticeable with the rgb moodlamp

**Comment by Hukuma1** [comment]
I thought my hardware was failing. Very noticeable on YouTube videos with compression artifacts.

**Comment by Kas152** [comment]
Thanks for this fix! Just one qustion though. Maybe I'm out of my depth here, but does it make sense to make a slider in stead of a ckeckbox for the dithering? In that way you can set the amount it dithers for each device seperately.
