### ISSUE TITLE
Stuck on White Lights 

### ISSUE THREAD

**Issue by Aarius** [psieg/Lightpack#46]
Windows 7 x64
2 Light-pack Units, Hardware v5?

Just completed first flash, 5_6.1.hex and installed unofficial prismatic 5.11.2.8 according to directions.

Now all lights are stuck on white light, non-responsive to screen movement, turning lights off or on, or closing of program. 
At zero brightness and gamma, lights remain lit white. 
At max brightness they intensify white.
On mood lamp, differing shades and brightness's of white light occur with manual color single color changes.
Performance has also crawled to 10 fps max.

Unsure what I did wrong.

Have tried all suggestions in the reddit forums, including DX Hooking, Luminosity (no response at all), Mood lamp, 

I have a couple logs but unsure how to include them

Sorry for the lack of technical info.. im PC savvy and have flashed Android ROMS but this just kicked my ass....

**Comment by psieg** [comment]
If they are non responsive to the on/off switch something went wrong when flashing the firmware.
First guess would be you flashed the wrong firmware for your hardware version. In the about tab, Prismatik shows the firmware version as e.g. 7.6 where 7 is hw version and 6 is sw version.
Since that will now be whatever you just flashed and I assume you didn't check it beforehand, the best thing to do is probably flashing 7.6+1 and seeing if that works, then 6.6+1 etc

**Comment by Aarius** [comment]
Great, thank you.

I followed you advice, reflashed until it worked.
