### ISSUE TITLE
[Question] Is current hooks utility code will always work for x64 platform build?

### ISSUE THREAD

**Issue by dreamer-dead** [psieg/Lightpack#72]
Hi!

Recently I found a library https://github.com/RaMMicHaeL/minhook
There is an article describing how it works - http://www.codeproject.com/Articles/44326/MinHook-The-Minimalistic-x-x-API-Hooking-Libra
It says that in x64 mode there are some problems with jumps to a detour function and some work should be done to avoid errors.

As I see, current version of the hooks library for x64 is the same as for x86, except some minor details. Am I right?

Maybe we can just use the library above to hook DX API?

**Comment by psieg** [comment]
From just skimming over the article, I got the following notes:
* Using the 32bit jump on a x64 process may result in the addressable address space being to small (not covering the injected target function). This may be a problem when using the 32bit JMP. I'm not sure whether this case can currently happen.
* The article refers to JMP-based injection. I prefer VMT-based injection, and that's AFAIR what the DX10/11 hook does. VMT-based means instead of changing the function, one changes the object's function pointer. It means one does not have to remove the JMP, run the orginal, and replace the JMP every time. This is different on 32bit and x64 because the address that is replaced also has double the bits = no problem
* Injection is somewhat "deprecated" as it is no longer needed on Windows 10. Since Windows 10 Desktop Duplication automatically covers fullscreen DirectX games. Additionally, the performance penalty of using (borderless) windowed mode have practically disappeared

**Comment by dreamer-dead** [comment]
That makes sense, thanks.
