### ISSUE TITLE
Hyperion Led Device over the lan

### ISSUE THREAD

**Issue by zapoc** [psieg/Lightpack#99]
Hi Psieg
First of all thanks for your fantastic fork

I was wondering if it would be possible to use a server hyperion over the network as a device?

I have a lot of hope in this function because there is a virtual led device in prismatik and hyperion offers the possibility of being controlled over the network

**Comment by psieg** [comment]
Hi,

it surely is possible, but it needs to be built from the ground up, as currently there is no Hyperion support at all.
I'm afraid I don't have enough time (and I can't test it), but if someone wants to work on it, please feel free to create a PR.

**Comment by psieg** [comment]
Cleaning up old issues

**Comment by nirkons** [comment]
Adding a workaround as a solution to this if someone is interested:
Instead of directly connecting the LEDs to an RPI/RPI+Arduino/etc.., you can use an ESP8266/ESP32 with WLED, and someone made a plugin for prismatik for WLED https://github.com/Lord-FEAR/Prismatik-WLED-WiFi

WLED supports adalight and TPM2, so you can keep the serial connection to Hyperion if you want (though Hyperion also supports WLED as a configuration option).

This way the same LED strip can be controlled via Hyperion and Prismatik at any given moment (either through Serial or UDP)

**Comment by nirkons** [comment]
> you don't need a plugin for WLED, it's supported natively now

Yes I know but Is it possible to control my Arduino Adalight via usb serial + 2 WLED devices all simultaneously without using the plugin?

thanks

**Comment by zomfg** [comment]
if you replace your Arduino with another WLED (or anything that speaks the protocol), you could control all 3, like [here](https://github.com/psieg/Lightpack/issues/149#issuecomment-680306712)

**Comment by nirkons** [comment]
Also a good option (I'm also aware of the option to use the WLED broadcast address), I'd rather have native integration honestly.

However, this way I can have 3 strips of different lengths (with some duplication and tweaking of the WLED plugin code),
I hope though in the future it would just be possible to add multiple devices in Prismatik, that would be amazing.

**Comment by zomfg** [comment]
directly talking to UDP is more optimal than that plugin (which is polling data from Prismatik and forwards it to the same UDP, and only talks 1 protocol,.. and needs python I guess)
so the recommended way is to try to achieve whatever directly with WLED (through broadcast and/or maybe with [groups/sync](https://github.com/Aircoookie/WLED/wiki/Sync-WLED-devices-(UDP-Notifier)))
and if that turns out impossible for a specific use case (you absolutely need to mix serial/udp for example), then sure
